export type P18PriorityTier = 1 | 2 | 3 | 4;

export interface P18GameClarityProfile {
  id: string;
  title: string;
  objective: string;
  essential: readonly string[];
  secondary: readonly string[];
  masteryName: string;
  mastery: string;
  danger: string;
  benefit: string;
  failure: string;
  nextTry: string;
  sourceControls: string;
  visualRedundancy: string;
  firstRunHint?: string;
  priority: P18PriorityTier;
  highSpeed: boolean;
}

/**
 * P18 teaching contracts. These describe existing gameplay; they never alter
 * simulation, scoring, timing, balance, hitboxes, or mastery eligibility.
 */
export const P18_GAME_CLARITY_PROFILES: readonly P18GameClarityProfile[] = Object.freeze([
  { id: 'orbit', title: 'Orbit', objective: 'Survive by staying in safe orbital lanes and following crystal routes.', essential: ['Tap / Space — pulse one lane', 'Up / Down — change lane'], secondary: ['A / D — reverse orbit direction'], masteryName: 'Route & Graze Mastery', mastery: 'Follow route crystals and graze comets only after they pass; formation warnings name the SAFE lane.', danger: 'Comets and threat formations crossing your current lane.', benefit: 'Route crystals, safe formations, and controlled grazes.', failure: 'A collision means your lane or timing was unsafe.', nextTry: 'Read the SAFE-lane telegraph before committing to the next pulse.', sourceControls: 'Tap / Space: Pulse • Up/Down: Lane • A/D: Reverse', visualRedundancy: 'Safe lanes are named in text and separated by position; hazards use silhouettes as well as color.', priority: 4, highSpeed: false },
  { id: 'stack', title: 'Stack', objective: 'Place each moving block on the tower and keep enough overlap to continue.', essential: ['Click / Tap / Space — place block'], secondary: ['F / Shift — arm Focus when available'], masteryName: 'Focus', mastery: 'Three consecutive perfect placements earn Focus; arm it to wager on a tighter 2px perfect window.', danger: 'Too little overlap ends the run.', benefit: 'Centered placements preserve tower width; PERFECT placements build Focus.', failure: 'The cut edge shows the missed overlap; no overlap ends the tower.', nextTry: 'Track the moving block edge against the block below instead of the screen center.', sourceControls: 'Click / Tap / Space • F / Shift: Focus', visualRedundancy: 'Moving/placed geometry, cut edges, PERFECT text, and Focus labels do not rely on color alone.', firstRunHint: 'PLACE THE MOVING BLOCK OVER THE TOWER', priority: 1, highSpeed: false },
  { id: 'reaction', title: 'Reaction', objective: 'Respond only to valid cues, using the requested direction when one is shown.', essential: ['Tap / Space — respond to a valid neutral cue', 'A / D or Left / Right — answer directional cues'], secondary: ['Do nothing on HOLD decoys'], masteryName: 'Inhibition & Overtime', mastery: 'Clean restraint on HOLD cues and a strong core run unlock the higher-risk overtime rounds.', danger: 'Responding early, choosing the wrong direction, or reacting to HOLD.', benefit: 'Fast correct responses and successful inhibition.', failure: 'FALSE START, WRONG, and TIMEOUT identify different mistakes.', nextTry: 'Read the cue type before reacting; speed matters only after the cue is classified.', sourceControls: 'Tap / Space • Choice: A/D or Left/Right', visualRedundancy: 'HOLD and directional cues use explicit words/directions in addition to color.', firstRunHint: 'ACT ON VALID CUES — IGNORE HOLD', priority: 1, highSpeed: false },
  { id: 'dodge', title: 'Dodge', objective: 'Survive the hazard field while collecting useful pickups and chaining safe Phase Cuts.', essential: ['Drag / Mouse / Arrows — steer'], secondary: ['Space — Warp Dash / Phase Cut'], masteryName: 'Phase Cut', mastery: 'During Warp Dash, deliberately cross hazards inside the brief phase window to score Phase Cuts and accelerate recharge.', danger: 'Any hazard contact outside the active phase window.', benefit: 'Powerups, safe space, and intentional Phase Cuts.', failure: 'The colliding hazard is the cause of the hit.', nextTry: 'Reserve Warp Dash for dense patterns where one dash can cross several threats safely.', sourceControls: 'Touch Drag / Mouse / Arrows • Space: Warp Dash / Phase Cut', visualRedundancy: 'Player, hazards, pickups, and active phase state differ by silhouette/effect as well as color.', priority: 3, highSpeed: true },
  { id: 'pulse', title: 'Pulse', objective: 'Tap when the expanding pulse reaches the timing target and sustain accurate rhythm.', essential: ['Click / Tap / Space — hit the beat'], secondary: ['F / Shift — arm Sync Wager when earned'], masteryName: 'Sync Wager', mastery: 'Every four-hit combo earns a wager; arm it to attempt a tighter bonus window on the next beat.', danger: 'Tapping outside the judgement window or breaking a wager.', benefit: 'GOOD, GREAT, and PERFECT results build combo and Fever.', failure: 'MISS and wager-failure labels explain the broken timing chain.', nextTry: 'Watch the ring-to-target distance and keep a steady internal pulse instead of reacting late.', sourceControls: 'Click / Tap / Space • F / Shift: Sync Wager', visualRedundancy: 'Judgement words and geometry communicate accuracy in addition to color.', firstRunHint: 'TAP AS THE PULSE REACHES THE TARGET', priority: 1, highSpeed: false },
  { id: 'merge', title: 'Merge', objective: 'Place the queued tile to build merges, cascades, and the current contract.', essential: ['Tap a column / Keys 1–4 — place tile'], secondary: ['Use the visible queue and earned tactical tools'], masteryName: 'Contract & Cascade Planning', mastery: 'Plan three tiles ahead, engineer cascades, and complete rotating contracts to recharge tactical tools.', danger: 'Filling the board without creating useful merge space.', benefit: 'Cascades, contract progress, swaps, and hammer charges.', failure: 'A blocked board means previous placements removed future merge options.', nextTry: 'Plan for the next three tiles, not just the current merge.', sourceControls: 'Tap Column / Keys 1–4', visualRedundancy: 'Tile values, board position, queue order, and tool labels provide non-color state information.', priority: 4, highSpeed: false },
  { id: 'typerush', title: 'Type Rush', objective: 'Type visible words before they cross the danger line.', essential: ['Physical keyboard / on-screen keypad — type letters'], secondary: ['Typing auto-locks the most urgent matching word'], masteryName: 'Threat Prioritization', mastery: 'Later directives reward choosing urgent and special threats instead of simply finishing the nearest easy word.', danger: 'Any unfinished word reaching the danger line.', benefit: 'Completed urgent/special words and directive-aligned targets.', failure: 'The escaped word and lane show what reached the line.', nextTry: 'Prioritize the word with the least remaining travel time before chasing multiplier value.', sourceControls: 'Physical Keyboard / On-Screen Keypad', visualRedundancy: 'Target text, typed-progress text, lane position, and danger-line geometry remain meaningful without color.', firstRunHint: 'TYPE ANY VISIBLE WORD BEFORE IT REACHES THE LINE', priority: 1, highSpeed: false },
  { id: 'oneline', title: 'One Line', objective: 'Draw one continuous ramp that lets the object reach the portal.', essential: ['Click & Drag / Touch Drag — draw the ramp'], secondary: ['Watch the ink budget; stars are optional for ordinary clears'], masteryName: 'Master Route', mastery: 'Master Route goals combine star collection with efficient ink use; the portal remains the core clear condition.', danger: 'Running out of useful ink or creating a path that loses the object before the portal.', benefit: 'Stable contacts, optional stars, and an efficient portal route.', failure: 'The final contact and motion show where the physical route stopped working.', nextTry: 'Use fewer, smoother slope changes so momentum survives the route.', sourceControls: 'Click & Drag / Touch Draw', visualRedundancy: 'Ink amount, line geometry, stars, and portal shape communicate state beyond color.', firstRunHint: 'DRAW ONE RAMP — THEN LET PHYSICS RUN', priority: 2, highSpeed: false },
  { id: 'breakout', title: 'Breakout Mini', objective: 'Keep the ball alive and clear the brick field.', essential: ['Mouse / Touch / Arrow Keys — move paddle'], secondary: ['Catch marked powerups when the route is safe'], masteryName: 'Round Contracts', mastery: 'Optional contracts reward combo, power, armor, and special-brick goals without changing the basic clear condition.', danger: 'Letting every active ball pass below the paddle.', benefit: 'Brick clears, powerups, multiball, and contract progress.', failure: 'A drain means the paddle failed to intercept the ball path.', nextTry: 'Meet the ball earlier with paddle position instead of chasing it after the bounce.', sourceControls: 'Mouse Drag / Touch / Arrow Keys', visualRedundancy: 'Brick durability, powerup marks, ball/paddle shapes, and contract text supplement color.', priority: 4, highSpeed: false },
  { id: 'perfectstop', title: 'Perfect Stop', objective: 'Stop the moving marker as close to the target center as possible.', essential: ['Click / Tap / Space — stop marker'], secondary: ['Read the changing sweep behavior each sector'], masteryName: 'Master Encore', mastery: 'Enough GREAT/PERFECT stops across the core sectors qualify the optional three-sector Master Encore.', danger: 'Stopping far outside the target or failing the required precision.', benefit: 'Closer stops earn stronger judgement and Encore qualification.', failure: 'The stopped marker remains positioned against the target so the error direction is visible.', nextTry: 'Anticipate the marker speed and press slightly before visual center at faster sweeps.', sourceControls: 'Click / Tap / Space', visualRedundancy: 'Target boundaries, stopped-marker position, and judgement text communicate quality without color.', firstRunHint: 'STOP THE MARKER INSIDE THE TARGET', priority: 1, highSpeed: false },
  { id: 'chain', title: 'Chain', objective: 'Use three tactical detonations to reach the wave target with the largest useful cascade.', essential: ['Select Plasma / Tesla / Cryo', 'Click / Tap arena — place detonation'], secondary: ['Three charges per wave'], masteryName: 'Resonance Order', mastery: 'Match the visible rotating three-tool Resonance Order for an optional streak bonus.', danger: 'Spending charges without reaching the wave target or respecting shield/spacing constraints.', benefit: 'Large cascades, special-orb interactions, and ordered tool sequences.', failure: 'Remaining charges and unmet target explain why the wave failed.', nextTry: 'Choose the tool that changes board structure before spending the next charge.', sourceControls: 'Select Tool • Click / Tap Arena • 3 Charges', visualRedundancy: 'Selected-tool labels/icons, charge count, target text, and orb structure supplement color.', firstRunHint: 'CHOOSE A TOOL — THEN PLACE UP TO 3 DETONATIONS', priority: 2, highSpeed: false },
  { id: 'gravity', title: 'Gravity', objective: 'Navigate each gravity sector to its warp beacon while using orbital forces deliberately.', essential: ['Drag — launch / slingshot', 'Touch / A / D — steer in flight'], secondary: ['Space — boost', 'G — flip polarity'], masteryName: 'Flight Contracts', mastery: 'Each sector advertises an optional contract for star routes, boost discipline, polarity, or clean no-recall flight.', danger: 'Colliding with celestial hazards or losing a viable route.', benefit: 'Stars, controlled gravity assists, and contract completion before warp.', failure: 'Collision/recall state identifies whether the route or control choice failed.', nextTry: 'Use gravity to bend the route first; steer and boost as corrections rather than primary propulsion.', sourceControls: 'Slingshot Drag • Touch/A/D to Steer • [G] Flip', visualRedundancy: 'Bodies, stars, beacon geometry, contract text, and polarity state provide non-color cues.', firstRunHint: 'DRAG TO LAUNCH — LET GRAVITY BEND THE PATH', priority: 2, highSpeed: false },
  { id: 'blade', title: 'Laser Blade', objective: 'Swipe through valid targets while avoiding EMP bombs.', essential: ['Mouse Drag / Touch Swipe — slice'], secondary: ['Aim through target centers for precision'], masteryName: 'Razor', mastery: 'Center cuts build the optional Razor precision chain and stronger milestone rewards.', danger: 'Red EMP bombs and unsafe swipe paths.', benefit: 'Clean target slices, multi-target swipes, shields, and center cuts.', failure: 'Bomb/miss feedback is distinct from target-cut feedback.', nextTry: 'Plan one clean swipe through several safe targets instead of chasing each target separately.', sourceControls: 'Mouse Drag / Swipe Slice', visualRedundancy: 'Bomb/target silhouettes, center geometry, shields, and Razor text supplement color.', priority: 4, highSpeed: false },
  { id: 'pinball', title: 'Neon Pinball', objective: 'Keep the ball in play and score through table targets, bumpers, and multiball.', essential: ['A / D or Left / Right — flippers', 'Tap screen sides — flippers'], secondary: ['Hit drop targets to progress Multiball'], masteryName: 'Table Control', mastery: 'Control rebounds to complete drop-target sets and exploit Multiball instead of merely surviving.', danger: 'A ball passing through the drain when no save applies.', benefit: 'Bumpers, drop targets, controlled shots, and Multiball.', failure: 'The drain and ball-save state make lost-ball cause explicit.', nextTry: 'Use one flipper at a time when possible to aim rather than firing both reflexively.', sourceControls: 'A / D • Left/Right Arrow • Tap Sides', visualRedundancy: 'Physical table geometry, target lights/shapes, ball path, and drain position supplement color.', priority: 4, highSpeed: false },
  { id: 'chrono', title: 'Chrono Wave', objective: 'Rotate through the open sector of each contracting wave and survive the vortex.', essential: ['A / D or Left / Right — rotate'], secondary: ['Space / E — EMP', 'F / Shift — Focus Wager when earned'], masteryName: 'Focus Wager', mastery: 'After clean passes, arm Focus to attempt a tighter center-line pass for an optional bonus.', danger: 'Crossing the solid part of a contracting wall.', benefit: 'Clean gap passes, shards, EMP charge, and precise Focus passes.', failure: 'The wall impact shows which opening was missed.', nextTry: 'Move toward the next opening early, before the wall reaches the player radius.', sourceControls: 'A / D • Left/Right Arrow • [Space] EMP • F/Shift: Focus Wager', visualRedundancy: 'Open gap geometry, wall shape, shard icons, and Focus text supplement color.', priority: 4, highSpeed: false },
  { id: 'matrix', title: 'Memory Matrix', objective: 'Memorize the shown sequence, then reproduce it under the active protocol.', essential: ['Tap grid / QWE-ASD-ZXC / Numpad — enter sequence'], secondary: ['O — arm Overclock for the next round'], masteryName: 'Overclock', mastery: 'Overclock adds two nodes, accelerates playback, disables manual replay, and increases reward for the next round.', danger: 'Entering the wrong node or losing the sequence under a transformed protocol.', benefit: 'Correct sequence recall and intentionally chosen Overclock rounds.', failure: 'Wrong-node/life-loss feedback is separate from playback.', nextTry: 'Chunk the sequence into small spatial groups instead of memorizing isolated flashes.', sourceControls: 'Tap Grid / QWE-ASD-ZXC / Numpad • O: Overclock', visualRedundancy: 'Playback/input phases, grid position, node order, and protocol labels remain readable without color alone.', firstRunHint: 'WATCH FIRST — REPEAT THE SEQUENCE AFTER PLAYBACK', priority: 2, highSpeed: false },
  { id: 'drift', title: 'Cyber Drift', objective: 'Stay on the road, survive traffic pressure, and chain deliberate driving events.', essential: ['A / D or Arrow Keys — steer'], secondary: ['Space — Nitro'], masteryName: 'Style Routes', mastery: 'Follow the visible Style Route by performing Apex, Close Pass, and Nitro events in the shown order.', danger: 'Road hazards, rivals, and losing control at speed.', benefit: 'Clean apexes, close passes, controlled Nitro, and completed Style Routes.', failure: 'Collision position identifies the object or line that ended the run.', nextTry: 'Set up the next road position before using Nitro; speed magnifies poor alignment.', sourceControls: 'A / D • Arrow Keys • [Space] Nitro', visualRedundancy: 'Road boundaries, vehicle/hazard silhouettes, route text, and event labels supplement color.', priority: 3, highSpeed: true },
  { id: 'vanguard', title: 'Galaxy Vanguard', objective: 'Survive enemy waves, destroy threats, and defeat flagships.', essential: ['Mouse / Touch / Arrows — move ship'], secondary: ['Space — Nova Bomb'], masteryName: 'Combat Routing', mastery: 'Prioritize dense threat groups, weapon upgrades, and Nova timing to preserve safe movement lanes through boss pressure.', danger: 'Enemy bodies, bullets, and boss patterns.', benefit: 'Enemy kills, upgrades, pickups, and efficient Nova clears.', failure: 'Damage and lethal-hit feedback remain attached to the incoming threat.', nextTry: 'Move toward open space before the next wave closes the lane.', sourceControls: 'Mouse Drag / Touch / Arrows • [Space] Bomb', visualRedundancy: 'Ship/enemy/bullet silhouettes, boss structure, pickup shapes, and HUD text supplement color.', priority: 3, highSpeed: true },
  { id: 'slingshot', title: 'Orbital Slingshot', objective: 'Release from one orbit, enter the next gravity well, and continue through each warp sector.', essential: ['Click / Tap / Space — release orbit tangentially'], secondary: ['Read the current navigation mission before release'], masteryName: 'Navigation Missions', mastery: 'Optional missions reward lock-on launches, deep captures, stardust routes, and gold-trail precision.', danger: 'Overshooting a viable well or colliding on an unsafe transfer.', benefit: 'Stable captures, mission conditions, and controlled warp progression.', failure: 'Overshoot, collision, and failed-capture states are distinct.', nextTry: 'Release when your tangential direction points toward the next useful gravity well, not directly at its center.', sourceControls: 'Click / Tap / Space', visualRedundancy: 'Orbit path, well geometry, capture state, mission text, and trail quality supplement color.', firstRunHint: 'RELEASE TANGENTIALLY — ENTER THE NEXT GRAVITY WELL', priority: 2, highSpeed: false },
  { id: 'snake', title: 'Cyber Serpent', objective: 'Grow the serpent while avoiding lethal collisions and navigating evolving firewalls.', essential: ['Arrows / WASD / Swipe / D-Pad — steer'], secondary: ['Use wraparound portals as the grid evolves'], masteryName: 'Phase Thread', mastery: 'During Ghost Phase, cross unique firewall cells deliberately to build a Phase Thread and earn bounded time extensions.', danger: 'Wall/self collisions and unsafe firewall contact outside valid phase state.', benefit: 'Growth pickups, portals, safe routes, and unique firewall crossings during Ghost Phase.', failure: 'Wall, self, and firewall causes remain distinguishable.', nextTry: 'Preserve open turning space as the body grows instead of chasing the shortest route to food.', sourceControls: 'Arrow Keys / WASD / Swipe / D-Pad', visualRedundancy: 'Head/body geometry, portal shapes, firewall cells, phase text, and grid position supplement color.', priority: 2, highSpeed: false },
  { id: 'rhythm', title: 'Neon Rhythm Tapper', objective: 'Hit note heads on the judgement line and sustain hold notes through their full tails.', essential: ['D / F / J / K, 1–4, Arrows, or touch — hit lanes'], secondary: ['Keep the lane held for hold-note tails'], masteryName: 'Timing & Overdrive', mastery: 'PERFECT timing, chords, full holds, and sustained combo build the strongest rewards and Overdrive state.', danger: 'Late/early hits, missed notes, and releasing holds before the tail ends.', benefit: 'PERFECT/GREAT judgements, complete holds, chords, and combo.', failure: 'MISS and HOLD BREAK identify the affected timing action.', nextTry: 'Focus on the judgement line rather than following notes all the way down the lane.', sourceControls: 'D / F / J / K • 1 / 2 / 3 / 4 • Arrows • Tap Lanes', visualRedundancy: 'Lane position, note-head/tail geometry, judgement text, and hold state supplement lane color.', priority: 4, highSpeed: false },
  { id: 'tower', title: 'Gravity Tower Jumper', objective: 'Keep landing on higher platforms and climb the tower without falling or hitting lethal hazards.', essential: ['A / D, Left / Right, or touch halves — steer'], secondary: ['Space — micro-boost / wall-jump', 'F / Shift — Apex when charged'], masteryName: 'Apex Drive', mastery: 'Precision center landings build Apex charges; activate Apex for a faster higher-reward ascent window.', danger: 'Missing platforms, lasers, drones, and unsafe ascent lines.', benefit: 'Center landings, pickups, height, and controlled Apex windows.', failure: 'Laser contact and missed-platform falls remain separate causes.', nextTry: 'Align over the platform center before descending rather than correcting after the landing window begins.', sourceControls: 'A / D • Left/Right • Touch Halves • Space • F/Shift: Apex', visualRedundancy: 'Platform geometry, laser shape, avatar position, Apex meter/text, and height HUD supplement color.', priority: 3, highSpeed: true },
  { id: 'pacmaze', title: 'Cyber Pac-Runner', objective: 'Clear pellets while avoiding dangerous ghosts and using power windows deliberately.', essential: ['WASD / Arrows / Swipe — move'], secondary: ['F / Shift — Hunt Rush after a power pellet'], masteryName: 'Hunt Rush', mastery: 'A power pellet grants one Hunt Rush; activate it to shorten frightened time, speed ghosts up, and double capture rewards.', danger: 'Contact with a dangerous ghost.', benefit: 'Pellets, power pellets, safe captures, and efficient maze routing.', failure: 'Ghost collision and frightened-state expiry remain visible.', nextTry: 'Plan an escape route before entering a corridor with an approaching ghost.', sourceControls: 'WASD / Arrows / Swipe • F / Shift: Hunt Rush', visualRedundancy: 'Maze walls, ghost/player silhouettes, frightened behavior, pellet shapes, and Hunt text supplement color.', priority: 4, highSpeed: false },
  { id: 'flappyaero', title: 'Aero Pulse', objective: 'Thrust through gate openings and survive without touching gate boundaries.', essential: ['Click / Tap / Space — thrust'], secondary: ['F / Shift — Flow Boost when charged'], masteryName: 'Flow Boost', mastery: 'Three consecutive grazes earn Flow Boost; activate it for four seconds of faster 2x scoring.', danger: 'Gate collision, especially when the opening is moving.', benefit: 'Clean gate passes, stars, controlled grazes, and Flow charge.', failure: 'The gate edge touched by the craft identifies the collision.', nextTry: 'Use small corrective thrusts and aim for stable gate-center height before chasing grazes.', sourceControls: 'Click / Tap / Space • F / Shift: Flow Boost', visualRedundancy: 'Gate-opening geometry, craft silhouette, graze text, charge state, and Flow label supplement color.', firstRunHint: 'TAP TO THRUST THROUGH THE OPENING', priority: 1, highSpeed: true },
  { id: 'roadcross', title: 'Cyber Crosser', objective: 'Cross each district row safely and reach the next checkpoint.', essential: ['WASD / Arrows / Tap / Swipe — hop'], secondary: ['Use grass as reset lanes and ride barges across water'], masteryName: 'District Routing', mastery: 'Read each district rhythm, chain safe row advances, and reach checkpoints efficiently for escalating bonuses.', danger: 'Vehicles, trains, water without support, and the advancing pressure line.', benefit: 'Safe row progress, barges, grass resets, and checkpoints.', failure: 'Vehicle, train, and water failures are spatially distinct.', nextTry: 'Wait on safe rows to read traffic rhythm instead of treating every opening as mandatory.', sourceControls: 'WASD / Arrow Keys / Tap / Swipe', visualRedundancy: 'Lane type, vehicle/train/barges silhouettes, grass/water geometry, and checkpoint text supplement color.', priority: 2, highSpeed: true },
  { id: 'bubblebuster', title: 'Orb Cannon', objective: 'Match three or more orbs and keep the board from reaching the ceiling limit.', essential: ['Mouse / Touch / A-D — aim', 'Click / Space — shoot'], secondary: ['Q — swap current/next once per shot', 'F / Shift — arm Burst when charged'], masteryName: 'Burst & Cascade Planning', mastery: 'Combos and cascade drops earn Burst charges; spend one on a deterministic bomb shot before ceiling pressure becomes critical.', danger: 'Board growth that leaves no safe space before the ceiling descends.', benefit: 'Matches, hanging-cluster drops, swaps, combos, and Burst charges.', failure: 'Ceiling pressure and terminal board state show why the run ended.', nextTry: 'Aim for support connections that can drop whole clusters instead of only making the nearest match.', sourceControls: 'Aim: Mouse/Touch/A-D • Shoot: Click/Space • Q: Swap • F/Shift: Burst', visualRedundancy: 'Orb position, chamber order, match count, ceiling line, swap/Burst labels, and cluster geometry supplement color.', priority: 4, highSpeed: false },
  { id: 'astroblaster', title: 'Astro Blaster 360', objective: 'Survive 360° space combat by controlling inertia and destroying incoming threats.', essential: ['A / D or Left / Right — rotate', 'W / Up — thrust', 'Space — fire'], secondary: ['Shift / S — Hyperspace Warp'], masteryName: 'Newtonian Combat', mastery: 'Use inertia, controlled thrust, asteroid splitting, and Warp timing to create safe firing lines instead of constantly accelerating.', danger: 'Asteroids, fragments, UFO fire, and collision trajectories.', benefit: 'Threat kills, stardust, controlled drift, and well-timed Warp escapes.', failure: 'Ship impact remains attached to the incoming object or shot.', nextTry: 'Rotate first, then use short thrust bursts so you do not carry excess speed into the next threat.', sourceControls: 'A / D: Steer • W: Thrust • Space: Fire • Shift: Warp', visualRedundancy: 'Vector silhouettes, projectile trajectories, ship orientation, Warp state, and HUD text supplement color.', priority: 3, highSpeed: true },
  { id: 'laserrope', title: 'Laser Rope Reflex', objective: 'Read the current beam mode and use the correct jump or slide response.', essential: ['Space / W / ↑ / Jump — jump LOW and DUAL', 'S / ↓ / Slide — slide under HIGH'], secondary: ['F / Shift — Redline when earned'], masteryName: 'Redline', mastery: 'Five clean evasions earn Redline; activate it for four seconds of faster 2x-reward play.', danger: 'Contact with LOW, HIGH, or DUAL beam sweeps.', benefit: 'Clean evasions, shield protection, streaks, and Redline charge.', failure: 'Beam contact plus the visible mode identifies the wrong timing/body response.', nextTry: 'Read LOW/HIGH/DUAL before committing; react to mode first and speed second.', sourceControls: 'Jump: Space / W / ↑ • Slide: S / ↓ • Tap Buttons', visualRedundancy: 'LOW/HIGH/DUAL text, beam height/geometry, jump/slide body state, and warnings supplement color.', firstRunHint: 'LOW = JUMP • HIGH = SLIDE • DUAL = JUMP', priority: 1, highSpeed: true },
  { id: 'blockdrop', title: 'Cyber Block Drop', objective: 'Build complete horizontal lines without letting the stack reach the top.', essential: ['Arrows / WASD — move, rotate, soft drop', 'Space — hard drop'], secondary: ['C / Shift — Hold'], masteryName: 'Tetris & B2B', mastery: 'Use Hold/Next and the 7-bag to create four-line clears; consecutive Tetrises earn back-to-back mastery bonuses.', danger: 'Locking pieces so high that the next piece cannot enter safely.', benefit: 'Line clears, efficient wells, Tetrises, B2B, and clear chains.', failure: 'Lockout leaves the board state visible so the blocked spawn is understandable.', nextTry: 'Preserve a clean well and use Hold to avoid placements that create covered holes.', sourceControls: 'Arrows / WASD • Space: Hard Drop • C / Shift: Hold', visualRedundancy: 'Piece/ghost geometry, board occupancy, Hold/Next labels, line count, and Tetris/B2B text supplement color.', priority: 4, highSpeed: false },
  { id: 'knifetarget', title: 'Knife Target', objective: 'Throw blades into safe open arcs of the rotating core.', essential: ['Click / Tap / Space — throw'], secondary: ['Aim for optional gold Razor Marks when the arc is safe'], masteryName: 'Razor Marks', mastery: 'Hit relocating Razor Marks without striking existing blades to build precision chains and bonus payouts.', danger: 'Throwing into an occupied blade arc or unsafe rotating sector.', benefit: 'Safe embeds, stage clears, and optional Razor Mark hits.', failure: 'The collision point on the core shows why the throw was unsafe.', nextTry: 'Track the next open arc, not the current blade position, because the core keeps rotating during the throw.', sourceControls: 'Click / Tap / Space', visualRedundancy: 'Blade/core geometry, occupied arcs, Razor Mark shape, stage text, and collision point supplement color.', priority: 4, highSpeed: false },
  { id: 'airhockey', title: 'Neon Puck Smash', objective: 'Defend your goal and score more goals than the AI before the match ends.', essential: ['Mouse Drag / Touch / WASD — move mallet'], secondary: ['Space / F — Power Play when ready'], masteryName: 'Power Play', mastery: 'Clean defensive contacts and goals fill Power; activate it for a short stronger-contact offensive scoring window.', danger: 'Letting the puck cross your goal line while overcommitting the mallet.', benefit: 'Controlled clears, goals, defensive contacts, and Power charge.', failure: 'A conceded goal is spatially distinct from ordinary puck contact.', nextTry: 'Recover toward the center after attacking so the goal is not left open on the rebound.', sourceControls: 'Mouse Drag / Touch / WASD • Space / F: Power Play', visualRedundancy: 'Goal/mallet/puck geometry, score, timer, Power meter/text, and contact direction supplement color.', priority: 4, highSpeed: false },
  { id: 'neonrail', title: 'Neon Rail Shift', objective: 'Shift between rails to follow safe phrases, collect cores, and avoid blocked routes.', essential: ['A / D / Arrows / Tap Lane — shift rail'], secondary: ['Space — Phase', 'Shift — Surge when available'], masteryName: 'Phase & Surge', mastery: 'Use Phase for tactical route survival and earned Surge for higher-risk mastery streaks without obscuring the safe-lane phrase.', danger: 'Entering a blocked rail or missing a readable route transition at speed.', benefit: 'Safe phrase completion, cores, Phase timing, and Surge mastery.', failure: 'The blocked route remains visible at collision.', nextTry: 'Read one phrase ahead and shift early; late corrections become harder as rail speed rises.', sourceControls: 'A / D • Arrow Keys • Tap Lane • Space: Phase • Shift: Surge', visualRedundancy: 'Rail position, blocker geometry, phrase structure, Phase/Surge text, and core shapes supplement color.', priority: 3, highSpeed: true },
]);

export const P18_GAME_CLARITY_BY_ID = Object.freeze(
  Object.fromEntries(P18_GAME_CLARITY_PROFILES.map((profile) => [profile.id, profile])) as Record<string, P18GameClarityProfile>,
);

export const P18_GAME_TITLE_TO_ID = Object.freeze(
  Object.fromEntries(P18_GAME_CLARITY_PROFILES.map((profile) => [profile.title.toUpperCase(), profile.id])) as Record<string, string>,
);

export const P18_FIRST_RUN_HINT_IDS = Object.freeze(
  P18_GAME_CLARITY_PROFILES.filter((profile) => profile.firstRunHint).map((profile) => profile.id),
);
